module Ibex
  module Runtime
    class ParseError < StandardError
    end

    class Parser
      attr_accessor yydebug: bool
      attr_writer yydebug_output: IO

      def initialize: () -> void
      def do_parse: () -> untyped
      def yyparse: (untyped receiver, Symbol method_id) -> untyped
      def next_token: () -> ([untyped, untyped] | false | nil)
      def on_error: (Integer token_id, untyped value, Array[untyped] value_stack) -> untyped
      def token_to_str: (Integer token_id) -> String
      def yyerror: () -> nil
      def yyerrok: () -> nil
      def yyaccept: () -> nil
      def expected_tokens: () -> Array[String]
    end
  end

  ParseError: singleton(Runtime::ParseError)
end
