# frozen_string_literal: true
# rbs_inline: enabled

require_relative "action_method_source"
require_relative "ruby_ast"

module Ibex
  module Codegen
    # Generates static-check-only Ruby containing semantic action methods.
    class ActionSource
      include RubyAST

      # @rbs @automaton: IR::Automaton
      # @rbs @grammar: IR::Grammar
      # @rbs @omit_action_call: bool
      # @rbs @method_source: ActionMethodSource

      # @rbs (IR::Automaton automaton, ?omit_action_call: bool?) -> void
      def initialize(automaton, omit_action_call: nil)
        @automaton = automaton
        @grammar = automaton.grammar
        @omit_action_call = omit_action_call.nil? ? @grammar.options[:omit_action_call] : omit_action_call
        @method_source = ActionMethodSource.new(@grammar)
      end

      # @rbs () -> String
      def generate
        lines = [
          "# frozen_string_literal: true",
          "# Generated by Ibex #{grammar_digest_comment}.",
          "# Static-check-only semantic action shadow source.",
          "# DO NOT LOAD OR EXECUTE: runtime wiring and user code are intentionally absent.",
          ""
        ]
        modules, class_name = class_parts
        modules.each { |name| lines << "module #{name}" }
        lines << "class #{class_name}"
        append_ast(lines)
        append_value_printers(lines)
        append_actions(lines)
        lines << "end"
        modules.reverse_each { lines << "end" }
        "#{lines.join("\n")}\n"
      end

      private

      # @rbs (Array[String] lines) -> void
      def append_value_printers(lines)
        @grammar.value_printers.each do |printer|
          symbol = @grammar.symbol(printer[:symbol]) || raise(Ibex::Error, "missing printer symbol #{printer[:symbol]}")
          location = printer.fetch(:loc) #: IR::location
          append_method(lines, location, @method_source.value_printer_method_source(symbol.id, printer))
        end
      end

      # @rbs (Array[String] lines) -> void
      def append_actions(lines)
        @grammar.productions.each do |production|
          if production.node
            append_method(lines, production.node.fetch(:loc), ast_node_action_source(production))
          elsif composed_action?(production)
            append_composed_actions(lines, production)
          elsif production.action || !@omit_action_call
            append_action(lines, production)
          end
        end
      end

      # @rbs (Array[String] lines, IR::Production production) -> void
      def append_composed_actions(lines, production)
        plan = production.action&.composition&.dig(:plan)
        raise Ibex::Error, "missing action composition plan" unless plan

        plan.fetch(:steps).each_with_index do |step, index|
          next unless step[:code]

          append_method(
            lines, step.fetch(:loc),
            @method_source.composed_fragment_method_source(production, step, index)
          )
        end
      end

      # @rbs (Array[String] lines, IR::Production production) -> void
      def append_action(lines, production)
        location = production.action&.location || production.origin.fetch(:loc) #: IR::location
        append_method(lines, location, @method_source.compiled_action_method_source(production))
      end

      # @rbs (Array[String] lines, IR::location location, String source) -> void
      def append_method(lines, location, source)
        lines << ""
        lines << "  # Grammar action: #{location.fetch(:file).inspect}:" \
                 "#{location.fetch(:line)}:#{location.fetch(:column)}"
        # Keep action bytes at column zero. Ruby lexical nesting does not require
        # indentation, while changing it can invalidate <<HEREDOC terminators or
        # alter <<~HEREDOC dedentation.
        lines << source
      end

      # @rbs (IR::Production production) -> bool
      def composed_action?(production)
        production.action&.composition&.dig(:plan, :version) == 1
      end

      # @rbs () -> [Array[String], String]
      def class_parts
        parts = @grammar.class_name.split("::")
        [parts.take(parts.length - 1), parts.fetch(-1)]
      end

      # @rbs () -> String
      def grammar_digest_comment
        @automaton.grammar_digest.delete_prefix("sha256:").chars.first(12).join
      end
    end
  end
end
