# frozen_string_literal: true

module Ibex
  module Codegen
    # Generates an RBS declaration for the public surface of a generated parser.
    class RBS
      # @rbs @automaton: IR::Automaton
      # @rbs @grammar: IR::Grammar
      # @rbs @superclass: String
      # @rbs @omit_action_call: bool

      # @rbs (IR::Automaton automaton, ?superclass: String?, ?omit_action_call: bool?) -> void
      def initialize(automaton, superclass: nil, omit_action_call: nil)
        @automaton = automaton
        @grammar = automaton.grammar
        @superclass = superclass || @grammar.superclass || "Ibex::Runtime::Parser"
        @omit_action_call = omit_action_call.nil? ? @grammar.options[:omit_action_call] : omit_action_call
      end

      # @rbs () -> String
      def generate
        lines = ["# Generated by Ibex #{grammar_digest_comment}", ""]
        modules, class_name = class_parts
        modules.each { |name| lines << "module #{name}" }
        lines << "class #{class_name} < #{@superclass}"
        append_contract(lines)
        append_lexer_contract(lines)
        append_value_printer_signatures(lines)
        append_actions(lines)
        lines << "end"
        modules.reverse_each { lines << "end" }
        "#{lines.join("\n")}\n"
      end

      private

      # @rbs (Array[String] lines) -> void
      def append_contract(lines)
        lines.push("  PARSER_TABLE_FORMAT_VERSION: Integer",
                   "  GRAMMAR_DIGEST: String", "  STATE_COUNT: Integer", "  PRODUCTION_COUNT: Integer",
                   "  TOKEN_IDS: Hash[untyped, Integer]", "  TOKEN_NAMES: Hash[Integer, String]",
                   "  ACTIONS: untyped", "  GOTOS: untyped", "  DEFAULT_ACTIONS: Array[untyped]",
                   "  EAGER_REDUCTIONS: Hash[Integer, [:reduce, Integer]]",
                   "  PRODUCTIONS: Array[Hash[Symbol, untyped]]",
                   "  ERROR_MESSAGES: Hash[Integer, String | { id: String, message: String }]",
                   "  PARSER_TABLES: Hash[Symbol, untyped]", "  DEBUG_ENABLED: bool", "",
                   "  def self.parser_tables: () -> Hash[Symbol, untyped]")
        lines << "  SYMBOL_NAMES: Hash[Integer, String]" if @grammar.options[:cst] == true
        append_entry_contract(lines)
        append_parameter_contract(lines)
      end

      # @rbs (Array[String] lines) -> void
      def append_entry_contract(lines)
        return unless @grammar.starts.length > 1

        lines << "  ENTRY_STATES: Hash[Symbol, Integer]"
        @grammar.starts.each { |name| lines << "  def parse_#{name}: () -> untyped" }
      end

      # @rbs (Array[String] lines) -> void
      def append_parameter_contract(lines)
        parameters = @grammar.parser_parameters
        return if parameters.empty?

        parameters.each do |parameter|
          lines << "  @#{parameter[:name]}: #{parameter[:semantic_type] || 'untyped'}"
        end
        keywords = parameters.map do |parameter|
          "#{parameter[:name]}: #{parameter[:semantic_type] || 'untyped'}"
        end
        lines << ""
        lines << "  def initialize: (#{keywords.join(', ')}, **untyped) -> void"
      end

      # @rbs (Array[String] lines) -> void
      def append_lexer_contract(lines)
        lexer = @grammar.lexer
        return unless lexer

        lines.push(
          "  LEXER_STATES: Array[String]",
          "  LEXER_RULES_BY_STATE: Hash[Symbol, Array[Hash[Symbol, untyped]]]",
          "",
          "  def lex: (String | IO | Fiber source, ?file: String) -> self",
          "  def parse: (String | IO | Fiber source, ?file: String) -> untyped",
          "  def lexer_state: () -> Symbol",
          "  def lexer_state=: (Symbol | String state) -> Symbol",
          "  def next_token: () -> [untyped, untyped, Hash[Symbol, untyped]]"
        )
        lexer.rules.each do |rule|
          lines << "  private def _ibex_lexer_action_#{rule.id}: (String lexeme) -> untyped" if rule.action
        end
      end

      # @rbs (Array[String] lines) -> void
      def append_value_printer_signatures(lines)
        @grammar.value_printers.each do |printer|
          symbol = @grammar.symbol(printer[:symbol]) || raise(Ibex::Error, "missing printer symbol #{printer[:symbol]}")
          lines << ""
          lines << "  private def _ibex_value_printer_#{symbol.id}: " \
                   "(#{symbol.semantic_type || 'untyped'} value) -> untyped"
        end
      end

      # @rbs (Array[String] lines) -> void
      def append_actions(lines)
        actions = @grammar.productions.select { |production| action_method?(production) }
        return if actions.empty?

        lines << ""
        actions.each do |production|
          append_action_signature(lines, production)
          append_composed_fragment_signatures(lines, production) if composed_action?(production)
        end
      end

      # @rbs (Array[String] lines, IR::Production production) -> void
      def append_action_signature(lines, production)
        parameters = production.rhs.map { |symbol_id| semantic_type(symbol_id) }.join(", ")
        locations = Array.new(production.rhs.length, "untyped").join(", ")
        result = semantic_type(production.lhs)
        lookahead = composed_action?(production) ? ", untyped" : ""
        lines << "  private def _ibex_action_#{production.id}: " \
                 "([#{parameters}], Array[untyped], [#{locations}], Array[untyped], " \
                 "Ibex::Runtime::LocationSpan?#{lookahead}) -> #{result}"
      end

      # @rbs (Array[String] lines, IR::Production production) -> void
      def append_composed_fragment_signatures(lines, production)
        plan = production.action&.composition&.dig(:plan)
        raise Ibex::Error, "missing action composition plan" unless plan

        plan.fetch(:steps).each_with_index do |step, index|
          next unless step[:code]

          inputs = step.fetch(:inputs).map do |slot|
            composition_slot_type(production, plan, slot, index)
          end
          locations = Array.new(inputs.length, "untyped").join(", ")
          result = step[:result_type] || "untyped"
          lines << "  private def _ibex_inline_fragment_#{production.id}_#{index}: " \
                   "([#{inputs.join(', ')}], Array[untyped], [#{locations}], Array[untyped], " \
                   "Ibex::Runtime::LocationSpan?) -> #{result}"
        end
      end

      # @rbs (IR::Production production, Hash[Symbol, untyped] plan, Integer slot, Integer step_index) -> String
      def composition_slot_type(production, plan, slot, step_index)
        physical = plan.fetch(:physical)
        return semantic_type(production.rhs.fetch(slot)) if slot < physical

        prior_index = slot - physical
        raise Ibex::Error, "invalid composed action slot #{slot}" if prior_index >= step_index

        plan.fetch(:steps).fetch(prior_index)[:result_type] || "untyped"
      end

      # @rbs (IR::Production production) -> bool
      def action_method?(production)
        !!(production.action || !@omit_action_call)
      end

      # @rbs (IR::Production production) -> bool
      def composed_action?(production)
        production.action&.composition&.dig(:plan, :version) == 1
      end

      # @rbs (Integer symbol_id) -> String
      def semantic_type(symbol_id)
        symbol = @grammar.symbol_by_id(symbol_id) || raise(Ibex::Error, "missing grammar symbol id #{symbol_id}")
        symbol.semantic_type || "untyped"
      end

      # @rbs () -> [Array[String], String]
      def class_parts
        parts = @grammar.class_name.split("::")
        [parts.take(parts.length - 1), parts.fetch(-1)]
      end

      # @rbs () -> String
      def grammar_digest_comment
        @automaton.grammar_digest.delete_prefix("sha256:").chars.first(12).join
      end
    end
  end
end
