# frozen_string_literal: true

module Ibex
  module Codegen
    # Generates a standalone Ruby parser class from Automaton IR.
    class Ruby
      def initialize(automaton, table: :compact, embedded: false, line_convert: true, debug: false,
                     omit_action_call: nil, superclass: nil, executable: nil)
        @automaton = automaton
        @grammar = automaton.grammar
        @table_format = table.to_sym
        @embedded = embedded
        @line_convert = line_convert
        @debug = debug
        @omit_action_call = omit_action_call.nil? ? @grammar.options[:omit_action_call] : omit_action_call
        @superclass = superclass || @grammar.superclass || "Ibex::Runtime::Parser"
        @executable = executable
      end

      def generate
        lines = []
        lines << "#!#{@executable}" if @executable
        lines.push("# frozen_string_literal: true", "# Generated by Ibex #{grammar_digest_comment}", "")
        append_user_code(lines, "header")
        append_runtime(lines)
        modules, class_name = class_parts
        modules.each { |name| lines << "module #{name}" }
        lines << "class #{class_name} < #{@superclass}"
        append_tables(lines)
        append_actions(lines)
        append_user_code(lines, "inner", indent: 2)
        private_actions(lines)
        lines << "end"
        modules.reverse_each { lines << "end" }
        append_user_code(lines, "footer")
        "#{lines.join("\n")}\n"
      end

      private

      def append_runtime(lines)
        if @embedded
          lines << embedded_source("../runtime/parser.rb")
          lines << embedded_source("../../ibex/tables.rb")
        else
          lines << 'require "ibex/runtime"'
          lines << 'require "ibex/tables"' if @table_format == :compact
        end
        lines << ""
      end

      def embedded_source(relative_path)
        path = File.expand_path(relative_path, __dir__)
        File.read(path).lines.reject { |line| line.start_with?("# frozen_string_literal:") }.join.rstrip
      end

      def append_tables(lines)
        table_set = Tables.build(@automaton, format: @table_format)
        indent = "  "
        lines << "#{indent}TOKEN_IDS = #{token_ids_literal}.freeze"
        lines << "#{indent}TOKEN_NAMES = #{token_names_literal}.freeze"
        lines << "#{indent}ACTIONS = #{table_literal(table_set.actions)}"
        lines << "#{indent}GOTOS = #{table_literal(table_set.gotos)}"
        lines << "#{indent}PRODUCTIONS = #{productions_literal}.freeze"
        lines << "#{indent}PARSER_TABLES = { tokens: TOKEN_IDS, token_names: TOKEN_NAMES, actions: ACTIONS,"
        lines << "#{indent}                  gotos: GOTOS, productions: PRODUCTIONS }.freeze"
        lines << "#{indent}def self.parser_tables = PARSER_TABLES"
        lines << "#{indent}DEBUG_ENABLED = #{@debug}"
        lines << ""
      end

      def table_literal(table)
        return "#{table.inspect}.freeze" unless table.is_a?(Tables::Compact)

        "Ibex::Tables::Compact.new(offsets: #{table.offsets.inspect}, values: #{table.values.inspect}, " \
          "checks: #{table.checks.inspect}, row_count: #{table.row_count})"
      end

      def token_ids_literal
        pairs = @grammar.terminals.filter_map do |terminal|
          next if terminal.id.zero? || terminal.name == "error"

          "#{external_token_expression(terminal)} => #{terminal.id}"
        end
        "{ #{pairs.join(', ')} }"
      end

      def external_token_expression(terminal)
        conversion = @grammar.conversions[terminal.name]
        return "(#{conversion})" if conversion
        return terminal.name if terminal.name.start_with?("'", '"')

        ":#{terminal.name}"
      end

      def token_names_literal
        entries = @grammar.terminals.map { |terminal| "#{terminal.id} => #{terminal.name.inspect}" }
        "{ #{entries.join(', ')} }"
      end

      def productions_literal
        entries = @grammar.productions.map do |production|
          action = action_method?(production) ? ":_ibex_action_#{production.id}" : "nil"
          "{ lhs: #{production.lhs}, length: #{production.rhs.length}, action: #{action} }"
        end
        "[#{entries.join(', ')}]"
      end

      def append_actions(lines)
        @grammar.productions.each do |production|
          next unless action_method?(production)

          append_action_constant(lines, production)
          append_action_method(lines, production)
        end
      end

      def append_action_constant(lines, production)
        return unless production.action && @line_convert

        lines << "  ACTION_CODE_#{production.id} = #{production.action.code.inspect}.freeze"
      end

      def append_action_method(lines, production)
        action = production.action
        lines << "  def _ibex_action_#{production.id}(val, _values)"
        lines << "    val = _values.last(#{action.context_length})" if action&.context_length&.positive?
        append_named_bindings(lines, action)
        if action
          append_semantic_code(lines, production)
        else
          lines << "    val[0]"
        end
        lines << "  end"
        lines << ""
      end

      def append_named_bindings(lines, action)
        return unless action&.named_refs&.any?

        action.named_refs.each { |reference| lines << "    #{reference[:name]} = val[#{reference[:index]}]" }
        names = action.named_refs.map { |reference| reference[:name] }
        lines << "    _ibex_named_values = [#{names.join(', ')}]"
      end

      def append_semantic_code(lines, production)
        action = production.action
        lines << "    result = val[0]" if @grammar.options[:result_var]
        if @line_convert
          evaluation = "eval(ACTION_CODE_#{production.id}, binding, #{action.location[:file].inspect}, " \
                       "#{action.location[:line]})"
          lines << "    #{@grammar.options[:result_var] ? evaluation : "return #{evaluation}"}"
        else
          action.code.lines.each { |line| lines << "    #{line.rstrip}" }
        end
        lines << "    result" if @grammar.options[:result_var]
      end

      def private_actions(lines)
        productions = @grammar.productions.select { |production| action_method?(production) }
        names = productions.map { |production| ":_ibex_action_#{production.id}" }
        lines << "  private #{names.join(', ')}" unless names.empty?
      end

      def action_method?(production)
        production.action || !@omit_action_call
      end

      def append_user_code(lines, name, indent: 0)
        code = @grammar.user_code[name]
        return if code.nil? || code.empty?

        prefix = " " * indent
        code.lines.each { |line| lines << "#{prefix}#{line.rstrip}" }
        lines << ""
      end

      def class_parts
        parts = @grammar.class_name.split("::")
        [parts[0...-1], parts.last]
      end

      def grammar_digest_comment
        @automaton.grammar_digest.delete_prefix("sha256:")[0, 12]
      end
    end
  end
end
