# frozen_string_literal: true

require_relative "../runtime/parser"
require_relative "ruby_actions"

module Ibex
  module Codegen
    # Generates a standalone Ruby parser class from Automaton IR.
    class Ruby
      include RubyActions

      # @rbs @automaton: IR::Automaton
      # @rbs @grammar: IR::Grammar
      # @rbs @table_format: Symbol
      # @rbs @embedded: bool
      # @rbs @line_convert: bool
      # @rbs @line_convert_all: bool
      # @rbs @debug: bool
      # @rbs @omit_action_call: bool
      # @rbs @superclass: String
      # @rbs @executable: String?
      # @rbs @error_messages: Hash[Integer, String]

      # @rbs (IR::Automaton automaton, ?table: Symbol | String, ?embedded: bool, ?line_convert: bool,
      #   ?line_convert_all: bool, ?debug: bool, ?omit_action_call: bool?, ?superclass: String?,
      #   ?executable: String?, ?error_messages: Hash[Integer, String]) -> void
      def initialize(automaton, table: :compact, embedded: false, line_convert: true, debug: false,
                     line_convert_all: false, omit_action_call: nil, superclass: nil, executable: nil,
                     error_messages: {})
        @automaton = automaton
        @grammar = automaton.grammar
        @table_format = table.to_sym
        @embedded = embedded
        @line_convert = line_convert
        @line_convert_all = line_convert_all
        @debug = debug
        @omit_action_call = omit_action_call.nil? ? @grammar.options[:omit_action_call] : omit_action_call
        @superclass = superclass || @grammar.superclass || "Ibex::Runtime::Parser"
        @executable = executable
        @error_messages = error_messages.sort.to_h.freeze
      end

      # @rbs () -> String
      def generate
        lines = [] #: Array[String]
        lines << "#!#{@executable}" if @executable
        lines.push("# frozen_string_literal: true", "# Generated by Ibex #{grammar_digest_comment}", "")
        append_user_code(lines, "header")
        append_runtime(lines)
        modules, class_name = class_parts
        modules.each { |name| lines << "module #{name}" }
        lines << "class #{class_name} < #{@superclass}"
        append_tables(lines)
        append_actions(lines)
        append_user_code(lines, "inner", indent: 2)
        lines << "end"
        modules.reverse_each { lines << "end" }
        append_user_code(lines, "footer")
        "#{lines.join("\n")}\n"
      end

      private

      # @rbs (Array[String] lines) -> void
      def append_runtime(lines)
        if @embedded
          lines << embedded_source("../runtime/location_span.rb")
          lines << embedded_source("../runtime/parser.rb")
          lines << embedded_source("../runtime/jsonl_tracer.rb")
          lines << embedded_source("../../ibex/tables.rb")
        else
          lines << 'require "ibex/runtime"'
          lines << 'require "ibex/tables"' if @table_format == :compact
        end
        lines << ""
      end

      # @rbs (String relative_path) -> String
      def embedded_source(relative_path)
        path = File.expand_path(relative_path, File.dirname(__FILE__))
        File.read(path).lines.reject { |line| line.start_with?("# frozen_string_literal:") }.join.rstrip
      end

      # @rbs (Array[String] lines) -> void
      def append_tables(lines)
        table_set = Tables.build(@automaton, format: @table_format)
        indent = "  "
        lines << "#{indent}PARSER_TABLE_FORMAT_VERSION = #{Runtime::PARSER_TABLE_FORMAT_VERSION}"
        lines << "#{indent}TOKEN_IDS = #{token_ids_literal}.freeze"
        lines << "#{indent}TOKEN_NAMES = #{token_names_literal}.freeze"
        lines << "#{indent}ACTIONS = #{table_literal(table_set.actions)}"
        lines << "#{indent}GOTOS = #{table_literal(table_set.gotos)}"
        lines << "#{indent}DEFAULT_ACTIONS = #{table_set.default_actions.inspect}.freeze"
        lines << "#{indent}PRODUCTIONS = #{productions_literal}.freeze"
        lines << "#{indent}error_messages = #{error_messages_literal} # @type var error_messages: Hash[Integer, String]"
        lines << "#{indent}ERROR_MESSAGES = error_messages.freeze #: Hash[Integer, String]"
        lines << "#{indent}PARSER_TABLES = { format_version: PARSER_TABLE_FORMAT_VERSION,"
        lines << "#{indent}                  tokens: TOKEN_IDS, token_names: TOKEN_NAMES, actions: ACTIONS,"
        lines << "#{indent}                  gotos: GOTOS, default_actions: DEFAULT_ACTIONS,"
        lines << "#{indent}                  productions: PRODUCTIONS, error_messages: ERROR_MESSAGES }.freeze"
        if shareable_parser_tables?
          lines << "#{indent}Ractor.make_shareable(PARSER_TABLES) " \
                   "if defined?(Ractor) && Ractor.respond_to?(:make_shareable)"
        end
        lines << "#{indent}def self.parser_tables = PARSER_TABLES"
        lines << "#{indent}DEBUG_ENABLED = #{@debug}"
        lines << ""
      end

      # Custom conversion expressions can return caller-owned mutable or
      # inherently unshareable objects, so only standard token mappings are
      # safe to freeze transitively.
      # @rbs () -> bool
      def shareable_parser_tables?
        @grammar.conversions.empty?
      end

      # @rbs (untyped table) -> String
      def table_literal(table)
        return "#{table.inspect}.freeze" unless table.is_a?(Tables::Compact)

        "Ibex::Tables::Compact.new(offsets: #{table.offsets.inspect}, values: #{table.values.inspect}, " \
          "checks: #{table.checks.inspect}, row_count: #{table.row_count})"
      end

      # @rbs () -> String
      def token_ids_literal
        pairs = @grammar.terminals.filter_map do |terminal|
          next if terminal.id.zero? || terminal.name == "error"

          "#{external_token_expression(terminal)} => #{terminal.id}"
        end
        "{ #{pairs.join(', ')} }"
      end

      # @rbs (IR::GrammarSymbol terminal) -> String
      def external_token_expression(terminal)
        conversion = @grammar.conversions[terminal.name]
        return "(#{conversion})" if conversion
        return terminal.name if terminal.name.start_with?("'", '"')

        ":#{terminal.name}"
      end

      # @rbs () -> String
      def token_names_literal
        entries = @grammar.terminals.map do |terminal|
          "#{terminal.id} => #{(terminal.display_name || terminal.name).inspect}"
        end
        "{ #{entries.join(', ')} }"
      end

      # @rbs () -> String
      def productions_literal
        entries = @grammar.productions.map do |production|
          generated_action = action_method?(production)
          action = generated_action ? ":_ibex_action_#{production.id}" : "nil"
          location_action = generated_action ? ", location_action: true" : ""
          "{ lhs: #{production.lhs}, length: #{production.rhs.length}, action: #{action}#{location_action} }"
        end
        "[#{entries.join(', ')}]"
      end

      # @rbs () -> String
      def error_messages_literal
        return "{}" if @error_messages.empty?

        entries = @error_messages.map { |state, message| "#{state} => #{message.inspect}" }
        "{ #{entries.join(', ')} }"
      end

      # @rbs (Array[String] lines, String name, ?indent: Integer) -> void
      def append_user_code(lines, name, indent: 0)
        code = @grammar.user_code[name]
        return if code.nil? || code.empty?

        prefix = " " * indent
        chunks = @grammar.user_code_chunks.fetch(name, Array.new(0))
        if map_user_code?(name) && !chunks.empty?
          chunks.each do |chunk|
            location = chunk.location
            lines << "#{prefix}eval(#{chunk.code.dump}, binding, #{location[:file].inspect}, #{location[:line]})"
          end
        elsif @line_convert_all
          raise Ibex::Error, "(codegen):1:1: source locations are required to convert #{name} user code"
        else
          code.lines.each { |line| lines << "#{prefix}#{line.rstrip}" }
        end
        lines << ""
      end

      # @rbs (String name) -> bool
      def map_user_code?(name)
        @line_convert_all || (@line_convert && name == "inner")
      end

      # @rbs () -> [Array[String], String]
      def class_parts
        parts = @grammar.class_name.split("::")
        [parts.take(parts.length - 1), parts.fetch(-1)]
      end

      # @rbs () -> String
      def grammar_digest_comment
        @automaton.grammar_digest.delete_prefix("sha256:").chars.first(12).join
      end
    end
  end
end
