AllCops:
  CacheRootDirectory: tmp/rubocop_cache
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - "pkg/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 36

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 150

Metrics/ParameterLists:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false
