# frozen_string_literal: true

module Ibex
  module ErrorMessages
    # @rbs (IR::Automaton automaton, Array[Entry] entries) -> String
    def render_entries(automaton, entries)
      lines = [
        HEADER,
        "# Generated by `ibex errors --update`; sentences and IDs are stable review keys.",
        "# Edit only `| ` message lines.",
        ""
      ]
      entries.each { |entry| append_entry(lines, automaton, entry) }
      "#{lines.join("\n").rstrip}\n"
    end

    # @rbs (Array[String] lines, IR::Automaton automaton, Entry entry) -> void
    def append_entry(lines, automaton, entry)
      lines << entry_heading(entry)
      lines << "## #{entry.error_id}"
      lines << "# entry: #{entry.entry}" if entry.entry
      lines << "# state: #{entry.state}" if entry.state
      append_expected_tokens(lines, automaton, entry)
      lines << "# Add one or more `| ` lines to customize this error." unless entry.message
      entry.message&.split("\n", -1)&.each { |line| lines << "| #{encode_line(line)}" }
      lines.push("end", "")
    end

    # @rbs (Entry entry) -> String
    def entry_heading(entry)
      return "legacy-state: #{entry.state}" unless entry.sentence

      prefix = entry.status == :active ? "sentence" : "unreachable"
      "#{prefix}: #{entry.sentence.join(' ')}"
    end

    # @rbs (Array[String] lines, IR::Automaton automaton, Entry entry) -> void
    def append_expected_tokens(lines, automaton, entry)
      return unless entry.status == :active && entry.state

      expected = expected_tokens(automaton, automaton.states.fetch(entry.state))
      lines << "# expected: #{expected.empty? ? '(none)' : expected.join(', ')}"
    end

    # @rbs (String line) -> String
    def encode_line(line)
      line.gsub("\\", "\\\\").gsub("\t", "\\t").gsub("\r", "\\r")
    end

    # @rbs (IR::Automaton automaton, IR::AutomatonState state) -> Array[String]
    def expected_tokens(automaton, state)
      ordinary_terminals(automaton).filter_map do |terminal|
        action = state.actions[terminal.id] || state.default_action
        terminal.display_name || terminal.name unless error_action?(action)
      end
    end

    module_function :render_entries, :append_entry, :entry_heading, :append_expected_tokens, :encode_line,
                    :expected_tokens

    class << self
      private :render_entries, :append_entry, :entry_heading, :append_expected_tokens, :encode_line, :expected_tokens
    end
  end
end
