# frozen_string_literal: true

require "fileutils"
require "pathname"

ROOT = Pathname(__dir__).join("..").expand_path
OUTPUT = ROOT.join("tmp/site")
STATIC_ROOT = ROOT.join("site")
PLAYGROUND_OUTPUT = OUTPUT.join("playground")
RUBY_ENTRIES = %w[
  lib/ibex/version.rb
  lib/ibex/error.rb
  lib/ibex/tables.rb
  lib/ibex/runtime.rb
  lib/ibex/frontend.rb
  lib/ibex/ir.rb
  lib/ibex/normalize.rb
  lib/ibex/analysis.rb
  lib/ibex/lalr.rb
].freeze
REQUIRE_RELATIVE = /^\s*require_relative\s+["']([^"']+)["'].*$/
EMBEDDED_REQUIRE = %r{^\s*require\s+["']ibex/(?:runtime|tables)["'].*$}

def ruby_dependency_order(entries)
  visited = {}
  order = []
  visit = lambda do |path|
    path = path.expand_path
    return if visited[path]

    visited[path] = true
    source = path.read
    source.scan(REQUIRE_RELATIVE).flatten.each do |relative|
      dependency = path.dirname.join(relative)
      dependency = Pathname("#{dependency}.rb") unless dependency.extname == ".rb"
      raise "missing Ruby dependency #{dependency.relative_path_from(ROOT)}" unless dependency.file?

      visit.call(dependency)
    end
    order << path
  end
  entries.each { |entry| visit.call(ROOT.join(entry)) }
  order
end

def bundled_ruby_source
  files = ruby_dependency_order(RUBY_ENTRIES)
  sections = files.map do |path|
    source = path.read.gsub(REQUIRE_RELATIVE, "").gsub(EMBEDDED_REQUIRE, "")
    "# source: #{path.relative_path_from(ROOT)}\n#{source}"
  end
  [
    "# Generated by tool/build_site.rb. Do not edit.\n",
    *sections,
    ROOT.join("site/playground/analyzer.rb").read
  ].join("\n")
end

abort "refusing to write outside tmp/site" unless OUTPUT.to_s.start_with?(ROOT.join("tmp").to_s)

FileUtils.rm_rf(OUTPUT)
FileUtils.mkdir_p(PLAYGROUND_OUTPUT)
FileUtils.cp(STATIC_ROOT.join("index.html"), OUTPUT)
FileUtils.cp(STATIC_ROOT.join("styles.css"), OUTPUT)
FileUtils.cp(STATIC_ROOT.join("playground/index.html"), PLAYGROUND_OUTPUT)
PLAYGROUND_OUTPUT.join("ibex.rb").write(bundled_ruby_source)
OUTPUT.join(".nojekyll").write("")
