# frozen_string_literal: true

require "digest"
require "ripper"
require "yaml"

module Ibex
  module Quality
    # rubocop:disable Metrics/ClassLength, Metrics/AbcSize, Metrics/MethodLength
    # rubocop:disable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity, Naming/PredicateMethod
    # One closed scanner/validator owns source binding, policy validation, and the deterministic public projection.
    # Statically binds every production OptionParser registration to an owner decision.
    class ConfigurationInventory
      ROOT = File.expand_path("../..", __dir__)
      REGISTRY = "test/fixtures/configuration/options-v1.yml"
      DOCUMENT = "docs/declarative-configuration.md"
      SOURCE_GLOBS = ["lib/ibex/cli.rb", "lib/ibex/cli/**/*.rb"].freeze
      OWNER_CLASSES = %w[grammar_contract grammar_minimum project_build_policy invocation_request].freeze
      ADMISSION_RESULTS = %w[
        admitted_a1_a8
        deferred_a5_minimum_undefined
        excluded_x1_operation
        excluded_x2_path_or_destination
        excluded_x3_presentation
        excluded_x4_caller_budget
        excluded_x5_packaging_or_deployment
        excluded_x7_diagnostic_suppression
      ].freeze
      OVERRIDE_ALGEBRAS = %w[
        fixed staged_fixed_compatibility minimum analysis_override project_selection invocation_only
      ].freeze
      IR_PRESENCE = %w[
        grammar_ir_v2_current
        automaton_ir_v2_only_contract_gap
        starts_current_strategy_gap
        cst_contract_gap
        not_persisted
      ].freeze
      MANIFEST_PRESENCE = %w[required current current_gap not_applicable].freeze
      COMPATIBILITY_STATES = %w[current obsolete_alias staged_compatibility internal_compatibility].freeze
      ROOT_KEYS = %w[schema_version scope registrations].freeze
      SCOPE_KEYS = %w[source_globs call_site_count runtime_registration_count].freeze
      ENTRY_KEYS = %w[
        id source method line declaration_sha256 context_sha256 surface declared_spellings effective_spellings
        canonical_key value_type default affected_stages public_contract_effect owner_class grammar_admission
        override_algebra ir_presence manifest_presence trust_implications compatibility_status
      ].freeze
      SHA256 = /\A[0-9a-f]{64}\z/
      KEY = /\A[a-z][a-z0-9]*(?:\.[a-z][a-z0-9_]*)+\z/

      Declaration = Struct.new(
        :id, :source, :method_name, :line, :declaration_sha256, :context_sha256, :declared_spellings, :spellings,
        :value_type,
        keyword_init: true
      )

      def initialize(root: ROOT, registry: nil, document: nil)
        @root = File.expand_path(root)
        @registry = registry || path(REGISTRY)
        @document = document || path(DOCUMENT)
      end

      def verify!
        inventory = load_inventory
        exact_keys!(inventory, ROOT_KEYS, "inventory")
        raise "configuration inventory schema_version must be 1" unless inventory.fetch("schema_version") == 1

        scope = inventory.fetch("scope")
        exact_keys!(scope, SCOPE_KEYS, "scope")
        unless scope.fetch("source_globs") == SOURCE_GLOBS
          raise "configuration inventory source_globs must match the reviewed production CLI scope"
        end

        declarations = declarations()
        call_site_count = declarations.map { |entry| [entry.source, entry.method_name, entry.line] }.uniq.length
        unless scope.fetch("call_site_count") == call_site_count
          raise "configuration inventory call_site_count drift: expected #{call_site_count}"
        end
        unless scope.fetch("runtime_registration_count") == declarations.length
          raise "configuration inventory runtime_registration_count drift: expected #{declarations.length}"
        end

        entries = inventory.fetch("registrations")
        raise "configuration inventory registrations must be an array" unless entries.is_a?(Array)

        expected_order = entries.sort_by { |entry| entry.fetch("id", "") }
        raise "configuration inventory registrations must use deterministic id order" unless entries == expected_order

        verify_exact_coverage(entries, declarations)
        verify_entries(entries, declarations.to_h { |declaration| [declaration.id, declaration] })
        verify_aliases(entries)
        verify_document!(entries)
        true
      end

      def render(entries = load_inventory.fetch("registrations"))
        counts = entries.group_by { |entry| entry.fetch("owner_class") }.transform_values(&:length)
        call_sites = entries.map { |entry| [entry.fetch("source"), entry.fetch("method"), entry.fetch("line")] }.uniq
        spelling_count = entries.sum { |entry| entry.fetch("effective_spellings").length }
        lines = [
          "# Declarative configuration inventory",
          "",
          "<!-- Generated by tool/quality/configuration_inventory.rb; edit options-v1.yml and regenerate. -->",
          "",
          "This inventory classifies every production `OptionParser#on` registration " \
          "without loading Ibex or user code.",
          "The admission decision follows `.idea/ibex-declarative-configuration-policy.md`: grammar-owned settings",
          "must pass A1-A8 and every X1-X7 exclusion remains outside grammar syntax.",
          "",
          "The static baseline is #{call_sites.length} source call sites and #{entries.length} runtime registrations:",
          "175 ordinary call sites plus 7 `fix` budget variants and 4 `import bison` budget variants.",
          "Those registrations expose #{spelling_count} effective spelling records after aliases and",
          "`--[no-]save-regression` are expanded; optional-argument notation remains one option pattern.",
          "",
          "Verification: `bundle exec rake quality:configuration_inventory`.",
          "Regeneration: `bundle exec ruby tool/quality/configuration_inventory.rb render`.",
          "",
          "## Decision rules",
          "",
          "This D001 artifact is inventory-only: it adds neither grammar syntax " \
          "nor the D002 effective-configuration model.",
          "`grammar_contract` is reserved for parser meaning/public contract and requires A1-A8, fixed semantics,",
          "root-only composition, provenance, and IR persistence. `project_build_policy` covers " \
          "representation and packaging.",
          "It also covers source mapping and companion artifacts rejected by X5.",
          "`invocation_request` covers operations, paths, presentation, caller budgets,",
          "and warning execution policy rejected by X1-X4 or X7.",
          "No current registration is classified as `grammar_minimum`: `test --coverage` remains an invocation request",
          "with admission deferred until user-production coverage and monotone merge are defined.",
          "",
          "| First-wave concept | Owner | Algebra | Current persistence status |",
          "|---|---|---|---|",
          markdown_row(["`grammar.mode`, `parser.superclass`, `actions.omit_calls`", "Grammar Contract",
                        "staged fixed compatibility", "Grammar IR v2; legacy CLI override needs D008"]),
          markdown_row(["`parser.algorithm`", "Grammar Contract", "fixed generation / explicit analysis override",
                        "Automaton IR only; grammar-contract persistence gap"]),
          markdown_row(["`parser.entries`", "Grammar Contract", "fixed generation / explicit analysis override",
                        "start symbols persist; isolation strategy gap"]),
          markdown_row(["`cst.trivia`", "Grammar Contract", "fixed", "IR and generation-manifest gaps"]),
          markdown_row(["table/runtime/debug/source mapping/companions", "Project Build Policy", "project selection",
                        "manifest records current generation choices"]),
          markdown_row(["emit/path/watch/report/budget/locale/help/warnings", "Invocation Request", "invocation only",
                        "excluded from Grammar IR"]),
          "",
          "Fixed means a future grammar declaration may be matched but not silently contradicted by generation CLI.",
          "Analysis commands may choose a different value only as an explicit noncanonical analysis override.",
          "The inventory records present compatibility gaps; it does not claim that later D002-D008 work is complete.",
          "",
          "## Owner summary",
          "",
          "| Owner class | Registrations |",
          "|---|---:|"
        ]
        OWNER_CLASSES.each { |owner| lines << "| `#{owner}` | #{counts.fetch(owner, 0)} |" }
        lines.push(
          "",
          "## Decisions",
          "",
          markdown_row([
                         "Surface", "CLI spelling / aliases", "Canonical concept", "Type / default", "Stages",
                         "Public-contract effect", "Owner", "Admission", "Override", "IR / manifest", "Trust",
                         "Compatibility", "Source"
                       ]),
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|"
        )
        entries.each do |entry|
          lines << "| #{cell(entry.fetch('surface'))} " \
                   "| #{cell(entry.fetch('effective_spellings').join(', '))} " \
                   "| `#{entry.fetch('canonical_key')}` " \
                   "| #{cell("#{entry.fetch('value_type')} / #{entry.fetch('default')}")} " \
                   "| #{cell(entry.fetch('affected_stages').join(', '))} " \
                   "| #{cell(entry.fetch('public_contract_effect'))} " \
                   "| `#{entry.fetch('owner_class')}` " \
                   "| `#{entry.fetch('grammar_admission')}` " \
                   "| `#{entry.fetch('override_algebra')}` " \
                   "| `#{entry.fetch('ir_presence')}` / `#{entry.fetch('manifest_presence')}` " \
                   "| #{cell(entry.fetch('trust_implications'))} " \
                   "| `#{entry.fetch('compatibility_status')}` " \
                   "| `#{entry.fetch('source')}:#{entry.fetch('line')}` |"
        end
        "#{lines.join("\n")}\n"
      end

      def write_document!
        File.binwrite(@document, render)
      end

      def declarations
        source_paths.flat_map { |relative| scan(relative) }.sort_by(&:id)
      end

      private

      def path(relative)
        File.join(@root, relative)
      end

      def source_paths
        SOURCE_GLOBS.flat_map { |glob| Dir.glob(path(glob)) }
                    .uniq.sort.map { |absolute| absolute.delete_prefix("#{@root}/") }
      end

      def scan(relative)
        source = File.binread(path(relative))
        sexp = Ripper.sexp(source)
        raise "cannot parse production CLI source #{relative}" unless sexp

        calls = []
        walk(sexp, nil, nil, calls)
        calls.flat_map do |call|
          spellings = option_spellings(call.fetch(:arguments))
          raise "#{relative}:#{call.fetch(:line)} OptionParser declaration has no static spelling" if spellings.empty?

          dynamic_context = dynamic?(spellings) ? dynamic_loop(call.fetch(:method_node), call.fetch(:line)) : nil
          expansions = expand_dynamic_spellings(spellings, dynamic_context)
          expansions.map do |effective_spellings|
            primary = effective_spellings.first
            identifier = "#{relative}##{call.fetch(:method)}##{primary}"
            Declaration.new(
              id: identifier,
              source: relative,
              method_name: call.fetch(:method),
              line: call.fetch(:line),
              declaration_sha256: digest_ast(call.fetch(:arguments)),
              context_sha256: dynamic_context ? digest_ast(dynamic_context) : nil,
              declared_spellings: spellings,
              spellings: effective_spellings,
              value_type: argument_value_type(call.fetch(:arguments), spellings)
            )
          end
        end
      end

      def walk(node, current_method, method_node, calls)
        return unless node.is_a?(Array)

        if node.first == :def
          name = node.fetch(1).fetch(1)
          node.drop(2).each { |child| walk(child, name, node, calls) }
          return
        end

        call = option_call(node)
        if call
          raise "OptionParser registration outside a named method" unless current_method && method_node

          calls << call.merge(method: current_method, method_node: method_node)
        end
        node.each { |child| walk(child, current_method, method_node, calls) if child.is_a?(Array) }
      end

      def option_call(node)
        case node.first
        when :method_add_arg
          call = node[1]
          return unless call&.first == :call && call.dig(3, 1) == "on"

          { line: call.dig(3, 2, 0), arguments: node.dig(2, 1, 1) || [] }
        when :command_call
          return unless node.dig(3, 1) == "on"

          { line: node.dig(3, 2, 0), arguments: node.dig(4, 1) || [] }
        end
      end

      def option_spellings(arguments)
        arguments.filter_map do |argument|
          rendered = render_string(argument)
          rendered if rendered&.start_with?("-")
        end
      end

      def argument_value_type(arguments, spellings)
        joined = spellings.join(" ")
        return "boolean" if joined.include?("[no-]")
        return "optional string or boolean" if joined.match?(/\[(?:=)?[A-Z]/)
        return "integer" if arguments.any? { |argument| constant_name(argument) == "Integer" }
        return "float" if arguments.any? { |argument| constant_name(argument) == "Float" }
        return "integer" if joined.match?(/=(?:N|PERCENT|SECONDS)\b/)
        return "enum" if arguments.any? { |argument| argument.is_a?(Array) && argument.first == :array }
        return "enum" if arguments.any? { |argument| constant_path?(argument) }
        return "boolean" unless joined.match?(/(?:=| )[A-Z]/)

        "string"
      end

      def constant_name(node)
        return unless node.is_a?(Array) && node.first == :var_ref && node.dig(1, 0) == :@const

        node.dig(1, 1)
      end

      def constant_path?(node)
        node.is_a?(Array) && %i[const_path_ref top_const_ref].include?(node.first)
      end

      def render_string(node)
        return unless node.is_a?(Array) && node.first == :string_literal

        content = node[1]
        return "" unless content&.first == :string_content

        content.drop(1).map do |part|
          case part.first
          when :@tstring_content
            part[1]
          when :string_embexpr
            token = find_identifier(part)
            token ? "\#{#{token}}" : "\#{...}"
          else
            ""
          end
        end.join
      end

      def find_identifier(node)
        return unless node.is_a?(Array)
        return node[1] if node.first == :@ident

        node.each do |child|
          found = find_identifier(child)
          return found if found
        end
        nil
      end

      def dynamic?(spellings)
        spellings.any? { |spelling| spelling.include?("\#{") }
      end

      def expand_dynamic_spellings(spellings, dynamic_context)
        return [spellings] unless dynamic?(spellings)

        raise "dynamic OptionParser declaration is not inside a static Hash#each loop" unless dynamic_context

        names = hash_string_keys(dynamic_context.dig(1, 1))
        raise "dynamic OptionParser declaration has no statically enumerable names" if names.empty?

        names.map do |name|
          spellings.map { |spelling| spelling.gsub(/\#\{[a-z_][a-z0-9_]*\}/, name) }
        end
      end

      def dynamic_loop(node, target_line)
        return unless node.is_a?(Array)

        if node.first == :method_add_block && node.dig(1, 0) == :call && node.dig(1, 3, 1) == "each" &&
           option_line?(node[2], target_line)
          return node
        end

        node.each do |child|
          found = dynamic_loop(child, target_line)
          return found if found
        end
        nil
      end

      def option_line?(node, target_line)
        return false unless node.is_a?(Array)
        return true if node.first == :@ident && node[1] == "on" && node.dig(2, 0) == target_line

        node.any? { |child| option_line?(child, target_line) }
      end

      def hash_string_keys(node, found = [])
        return found unless node.is_a?(Array)

        if node.first == :assoc_new
          value = render_string(node[1])
          found << value if value
        end
        node.each { |child| hash_string_keys(child, found) if child.is_a?(Array) }
        found
      end

      def digest_ast(node)
        Digest::SHA256.hexdigest(Marshal.dump(strip_positions(node)))
      end

      def strip_positions(node)
        return node unless node.is_a?(Array)
        return node.take(2) if node.first.to_s.start_with?("@")

        node.map { |child| strip_positions(child) }
      end

      def load_inventory
        value = YAML.safe_load(File.binread(@registry), permitted_classes: [], permitted_symbols: [], aliases: false)
        raise "configuration inventory root must be a mapping" unless value.is_a?(Hash)

        value
      rescue Psych::Exception => e
        raise "cannot load configuration inventory: #{e.message}"
      end

      def exact_keys!(mapping, expected, label)
        raise "#{label} must be a mapping" unless mapping.is_a?(Hash)

        actual = mapping.keys
        return if actual.sort == expected.sort

        raise "#{label} keys must be exactly #{expected.join(', ')}; got #{actual.join(', ')}"
      end

      def verify_exact_coverage(entries, declarations)
        ids = entries.map { |entry| entry.fetch("id", nil) }
        duplicates = ids.tally.select { |_id, count| count > 1 }.keys
        raise "configuration inventory duplicate registrations: #{duplicates.join(', ')}" unless duplicates.empty?

        expected = declarations.map(&:id)
        missing = expected - ids
        extra = ids - expected
        return if missing.empty? && extra.empty?

        raise "configuration inventory coverage drift; missing=#{missing.join(',')} extra=#{extra.join(',')}"
      end

      def verify_entries(entries, declarations)
        entries.each do |entry|
          id = entry.fetch("id", "unknown")
          exact_keys!(entry, ENTRY_KEYS, "registration #{id}")
          declaration = declarations.fetch(id)
          verify_source_binding(entry, declaration)
          verify_classification(entry)
        end
      end

      def verify_source_binding(entry, declaration)
        id = entry.fetch("id")
        {
          "source" => declaration.source,
          "method" => declaration.method_name,
          "line" => declaration.line,
          "declaration_sha256" => declaration.declaration_sha256,
          "context_sha256" => declaration.context_sha256,
          "declared_spellings" => declaration.declared_spellings,
          "value_type" => declaration.value_type
        }.each do |field, expected|
          raise "registration #{id} #{field} drift" unless entry.fetch(field) == expected
        end
        unless entry.fetch("declaration_sha256").match?(SHA256)
          raise "registration #{id} declaration_sha256 must be SHA-256"
        end
        return unless declaration.context_sha256 && !entry.fetch("context_sha256").to_s.match?(SHA256)

        raise "registration #{id} dynamic declaration must bind its enclosing method"
      end

      def verify_classification(entry)
        id = entry.fetch("id")
        nonempty_string!(entry.fetch("surface"), id, "surface")
        spellings = entry.fetch("effective_spellings")
        unless spellings.is_a?(Array) && !spellings.empty? && spellings.all? do |value|
          value.is_a?(String) && value.start_with?("-")
        end
          raise "registration #{id} effective_spellings must be a non-empty option array"
        end
        raise "registration #{id} effective_spellings must be unique" unless spellings.uniq == spellings

        key = entry.fetch("canonical_key")
        raise "registration #{id} has an unclassified canonical key" unless key.is_a?(String) && key.match?(KEY)

        %w[default public_contract_effect trust_implications].each do |field|
          nonempty_string!(entry.fetch(field), id, field)
        end
        stages = entry.fetch("affected_stages")
        unless stages.is_a?(Array) && !stages.empty? && stages.all? { |stage| stage.is_a?(String) && !stage.empty? }
          raise "registration #{id} affected_stages must be a non-empty string array"
        end

        enum!(entry, "owner_class", OWNER_CLASSES)
        enum!(entry, "grammar_admission", ADMISSION_RESULTS)
        enum!(entry, "override_algebra", OVERRIDE_ALGEBRAS)
        enum!(entry, "ir_presence", IR_PRESENCE)
        enum!(entry, "manifest_presence", MANIFEST_PRESENCE)
        enum!(entry, "compatibility_status", COMPATIBILITY_STATES)
        verify_owner_policy(entry)
      end

      def verify_owner_policy(entry)
        id = entry.fetch("id")
        owner = entry.fetch("owner_class")
        admission = entry.fetch("grammar_admission")
        override = entry.fetch("override_algebra")
        ir = entry.fetch("ir_presence")
        case owner
        when "grammar_contract"
          raise "registration #{id} grammar contract must pass A1-A8" unless admission == "admitted_a1_a8"
          unless %w[fixed staged_fixed_compatibility analysis_override].include?(override)
            raise "registration #{id} grammar contract has invalid override algebra"
          end
          raise "registration #{id} grammar contract must record its IR state" if ir == "not_persisted"
        when "grammar_minimum"
          raise "registration #{id} grammar minimum must use minimum algebra" unless override == "minimum"
        when "project_build_policy"
          unless admission == "excluded_x5_packaging_or_deployment" && override == "project_selection"
            raise "registration #{id} project build policy must be excluded by X5 and use project selection"
          end
        when "invocation_request"
          unless override == "invocation_only" && ir == "not_persisted"
            raise "registration #{id} invocation request must remain CLI-only"
          end
        end
      end

      def verify_aliases(entries)
        by_surface = entries.group_by { |entry| entry.fetch("surface") }
        by_surface.each do |surface, surface_entries|
          spellings = {}
          surface_entries.each do |entry|
            entry.fetch("effective_spellings").each do |spelling|
              normalized = spelling.sub(/(?:\[?=|\s)[A-Z][A-Z0-9_-]*\]?\z/, "")
              previous = spellings[normalized]
              if previous && previous.fetch("canonical_key") != entry.fetch("canonical_key")
                raise "surface #{surface} alias #{normalized} maps to multiple canonical concepts"
              end

              spellings[normalized] = entry
            end
          end
        end
        obsolete = entries.select { |entry| entry.fetch("compatibility_status") == "obsolete_alias" }
        obsolete.each do |entry|
          matches = entries.reject { |candidate| candidate.equal?(entry) }.select do |candidate|
            candidate.fetch("surface") == entry.fetch("surface") &&
              candidate.fetch("canonical_key") == entry.fetch("canonical_key")
          end
          raise "obsolete alias #{entry.fetch('id')} must point to a canonical registration" if matches.empty?
        end
      end

      def verify_document!(entries)
        expected = render(entries)
        actual = File.binread(@document)
        return if actual == expected

        raise "declarative configuration documentation is stale; regenerate it from the inventory"
      end

      def nonempty_string!(value, id, field)
        return if value.is_a?(String) && !value.strip.empty?

        raise "registration #{id} #{field} must be a non-empty string"
      end

      def enum!(entry, field, allowed)
        value = entry.fetch(field)
        return if allowed.include?(value)

        raise "registration #{entry.fetch('id')} #{field} must be one of #{allowed.join(', ')}"
      end

      def cell(value)
        value.to_s.gsub("|", "\\|").gsub("\n", " ")
      end

      def markdown_row(values)
        "| #{values.join(' | ')} |"
      end
    end
    # rubocop:enable Metrics/ClassLength, Metrics/AbcSize, Metrics/MethodLength
    # rubocop:enable Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity, Naming/PredicateMethod
  end
end

if $PROGRAM_NAME == __FILE__
  inventory = Ibex::Quality::ConfigurationInventory.new
  case ARGV.fetch(0, "check")
  when "check"
    inventory.verify!
  when "render"
    inventory.write_document!
  else
    warn "usage: ruby tool/quality/configuration_inventory.rb [check|render]"
    exit 64
  end
end
