# frozen_string_literal: true
# rbs_inline: enabled

require_relative "error"

module Ibex
  # Parses, validates, and deterministically updates state-specific syntax
  # error messages.
  module ErrorMessages
    HEADER = "# ibex-messages v1"

    # One active or archived state entry with its source line.
    class Entry
      attr_reader :state #: Integer
      attr_reader :status #: :active | :removed
      attr_reader :message #: String?
      attr_reader :line #: Integer

      # @rbs (state: Integer, status: :active | :removed, message: String?, line: Integer) -> void
      def initialize(state:, status:, message:, line:)
        @state = state
        @status = status
        @message = message&.freeze
        @line = line
        freeze
      end
    end

    # Immutable parsed messages document.
    class Document
      attr_reader :entries #: Array[Entry]

      # @rbs (entries: Array[Entry]) -> void
      def initialize(entries:)
        @entries = entries.freeze
        freeze
      end
    end

    require_relative "error_messages/parser"

    # @rbs (String source, file: String) -> Document
    def parse(source, file:)
      Parser.new(source, file: file).parse
    end
    module_function :parse

    # @rbs (String path) -> Document
    def load(path)
      parse(File.binread(path), file: path)
    end
    module_function :load

    # @rbs (IR::Automaton automaton) -> Array[IR::AutomatonState]
    def error_states(automaton)
      terminals = ordinary_terminals(automaton)
      automaton.states.select do |state|
        terminals.any? { |terminal| error_action?(state.actions[terminal.id] || state.default_action) }
      end.sort_by(&:id)
    end
    module_function :error_states

    # @rbs (IR::Automaton automaton, ?existing: Document?) -> String
    def render(automaton, existing: nil)
      previous = (existing || Document.new(entries: [])).entries.to_h { |entry| [entry.state, entry] }
      states = error_states(automaton)
      active_ids = states.to_h { |state| [state.id, true] }
      lines = [HEADER, "# Generated by `ibex errors --update`; edit only `| ` message lines.", ""]
      states.each do |state|
        append_entry(lines, :active, state.id, previous[state.id]&.message,
                     expected: expected_tokens(automaton, state))
      end

      removed = previous.values.reject { |entry| active_ids[entry.state] }.sort_by(&:state)
      unless removed.empty?
        lines.push("# States below are absent from the current syntax-error state set.", "")
        removed.each { |entry| append_entry(lines, :removed, entry.state, entry.message) }
      end
      "#{lines.join("\n").rstrip}\n"
    end
    module_function :render

    # @rbs (Document document, IR::Automaton automaton, file: String) -> Hash[Integer, String]
    def messages_for(document, automaton, file:)
      valid = error_states(automaton).to_h { |state| [state.id, true] }
      messages = {} #: Hash[Integer, String]
      document.entries.each do |entry|
        next if entry.status == :removed

        unless valid[entry.state]
          fail_at(file, entry.line, 1,
                  "unknown error state #{entry.state} for current automaton; run `ibex errors --update`")
        end
        messages[entry.state] = entry.message if entry.message
      end
      messages.sort.to_h.freeze
    end
    module_function :messages_for

    # @rbs (Array[String] lines, :active | :removed status, Integer state, String? message,
    #   ?expected: Array[String]?) -> void
    def append_entry(lines, status, state, message, expected: nil)
      lines << "#{status == :active ? 'state' : 'removed'} #{state}"
      lines << "# expected: #{expected.empty? ? '(none)' : expected.join(', ')}" if expected
      lines << "# Add one or more `| ` lines to customize this state." unless message
      message&.split("\n", -1)&.each { |line| lines << "| #{encode_line(line)}" }
      lines.push("end", "")
    end

    # @rbs (String line) -> String
    def encode_line(line)
      line.gsub("\\", "\\\\").gsub("\t", "\\t").gsub("\r", "\\r")
    end

    # @rbs (IR::Automaton automaton, IR::AutomatonState state) -> Array[String]
    def expected_tokens(automaton, state)
      ordinary_terminals(automaton).filter_map do |terminal|
        action = state.actions[terminal.id] || state.default_action
        terminal.display_name || terminal.name unless error_action?(action)
      end
    end

    # @rbs (IR::Automaton automaton) -> Array[IR::GrammarSymbol]
    def ordinary_terminals(automaton)
      automaton.grammar.terminals.reject { |terminal| terminal.name == "error" }
    end

    # @rbs (IR::parser_action? action) -> bool
    def error_action?(action)
      action.nil? || action[:type].to_sym == :error
    end

    # @rbs (String file, Integer line, Integer column, String message) -> bot
    def fail_at(file, line, column, message)
      raise Ibex::Error, "#{file}:#{line}:#{column}: #{message}"
    end
    module_function :append_entry, :encode_line, :expected_tokens, :ordinary_terminals, :error_action?, :fail_at

    class << self
      private :append_entry, :encode_line, :expected_tokens, :ordinary_terminals, :error_action?, :fail_at
    end
  end
end
