name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: '3.0'
            experimental: false
          - ruby: '3.1'
            experimental: false
          - ruby: '3.2'
            experimental: false
          - ruby: '3.3'
            experimental: false
          - ruby: '3.4'
            experimental: false
          - ruby: '4.0'
            experimental: false
          - ruby: 'head'
            experimental: false
          - ruby: jruby
            experimental: true
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
